---
- name: Setup database tier
  hosts: appdbs
  vars:
    postgresql_databases:
      - name: awx
        
    postgresql_users:
      - name: awx
        password: supersecure

  tags:
    - databases

  roles:
    - common
    - geerlingguy.postgresql

